<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CA1859</NoWarn>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Authors>RhiGhAI personal project</Authors>
    <Company>RhiGhAI personal project</Company>
    <Product>RhiGhAI</Product>
    <Copyright>Copyright © 2026</Copyright>
    <VersionPrefix>0.2.0</VersionPrefix>
  </PropertyGroup>
</Project>
