using System.Drawing;
using Grasshopper.Kernel;

namespace RhiGhAI.Grasshopper;

public sealed class RhiGhAIAssemblyInfo : GH_AssemblyInfo
{
    public override string Name => "RhiGhAI";
    public override Bitmap? Icon => null;
    public override string Description => "Controlled parametric modelling generated by RhiGhAI.";
    public override Guid Id => new("77E9594A-EA19-4C19-9800-1694632B64BE");
    public override string AuthorName => "RhiGhAI personal project";
    public override string AuthorContact => string.Empty;
}
